#spring.data.mongodb.uri=mongodb://localhost:27017/userdb
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ulmnlomltrawhgugbyrw
spring.datasource.password=QeNXK1ypQqayfQM0

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

